// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticaParcial.Persistence;

#nullable disable

namespace PracticaParcial.Migrations
{
    [DbContext(typeof(UnidadDbContext))]
    [Migration("20260611003915_Notificacion")]
    partial class Notificacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PracticaParcial.Models.Consorcios.Consorcio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiaVencimientoExpensas")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitud")
                        .HasColumnType("float");

                    b.Property<double>("Longitud")
                        .HasColumnType("float");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Consorcios");
                });

            modelBuilder.Entity("PracticaParcial.Models.Gastos.Gasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnioExpensa")
                        .HasColumnType("int");

                    b.Property<string>("ArchivoComprobante")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateOnly>("FechaGasto")
                        .HasColumnType("date");

                    b.Property<int>("IdConsorcio")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoGasto")
                        .HasColumnType("int");

                    b.Property<int>("MesExpensa")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdTipoGasto");

                    b.ToTable("Gastos");
                });

            modelBuilder.Entity("PracticaParcial.Models.Gastos.TipoGasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TiposGasto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Mantenimiento Gral"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Reparacion Unidad"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Comprar Limpieza"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Extraordinario"
                        });
                });

            modelBuilder.Entity("PracticaParcial.Models.Notificaciones.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("FechaDeCreacion")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaDeEnvio")
                        .HasColumnType("date");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("consorcioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("consorcioId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("PracticaParcial.Models.Reserva.ReservaSUM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EntregoCorrectamente")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Turno")
                        .HasColumnType("int");

                    b.Property<int>("UnidadId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnidadId");

                    b.ToTable("ReservasSUM");
                });

            modelBuilder.Entity("PracticaParcial.Models.Unidades.Unidad", b =>
                {
                    b.Property<int>("IdUnidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUnidad"));

                    b.Property<string>("ApellidoPropietario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ConsorcioId")
                        .HasColumnType("int");

                    b.Property<string>("EmailPropietario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("FechaCreacion")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NombrePropietario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Superficie")
                        .HasColumnType("int");

                    b.HasKey("IdUnidad");

                    b.HasIndex("ConsorcioId");

                    b.ToTable("Unidades");
                });

            modelBuilder.Entity("PracticaParcial.Models.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PracticaParcial.Models.Consorcios.Consorcio", b =>
                {
                    b.HasOne("PracticaParcial.Models.Users.User", "User")
                        .WithMany("Consorcios")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PracticaParcial.Models.Gastos.Gasto", b =>
                {
                    b.HasOne("PracticaParcial.Models.Gastos.TipoGasto", "TipoGasto")
                        .WithMany()
                        .HasForeignKey("IdTipoGasto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoGasto");
                });

            modelBuilder.Entity("PracticaParcial.Models.Notificaciones.Notificacion", b =>
                {
                    b.HasOne("PracticaParcial.Models.Consorcios.Consorcio", "consorcio")
                        .WithMany()
                        .HasForeignKey("consorcioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("consorcio");
                });

            modelBuilder.Entity("PracticaParcial.Models.Reserva.ReservaSUM", b =>
                {
                    b.HasOne("PracticaParcial.Models.Unidades.Unidad", "Unidad")
                        .WithMany("Reservas")
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("PracticaParcial.Models.Unidades.Unidad", b =>
                {
                    b.HasOne("PracticaParcial.Models.Consorcios.Consorcio", "Consorcio")
                        .WithMany("Unidades")
                        .HasForeignKey("ConsorcioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consorcio");
                });

            modelBuilder.Entity("PracticaParcial.Models.Consorcios.Consorcio", b =>
                {
                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("PracticaParcial.Models.Unidades.Unidad", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("PracticaParcial.Models.Users.User", b =>
                {
                    b.Navigation("Consorcios");
                });
#pragma warning restore 612, 618
        }
    }
}
